name: "Install composer deps"

inputs:
  os:
    description: 'OS version'
    required: true
  php:
    description: 'PHP version'
    required: true
  flags:
    description: 'Composer flags'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get Composer cache directory
      id: composer-cache-dir
      shell: bash
      run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT

    - name: Get Composer cache directory
      shell: bash
      run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

    - name: Get Composer cache directory 2
      shell: bash
      run: echo $COMPOSER_CACHE_DIR

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: AA-${{ env.COMPOSER_CACHE_DIR }}-${{ inputs.os }}-${{ inputs.php }}-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          AA-${{ inputs.os }}-${{ inputs.php }}-${{ hashFiles('**/composer.json') }}-
          AA-${{ inputs.os }}-${{ inputs.php }}-

    - name: Install dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 30
        # `--no-scripts` to avoid side-effects (e.g. installing dev-tools for all jobs on CI level),
        # all executed scripts should be explicit and run only when needed.
        command: composer update --optimize-autoloader --no-interaction --no-progress --no-scripts ${{ inputs.flags }}

    - name: Report versions
      shell: bash
      run: composer info -D
